### ISSUE TITLE
Book.java needs immediate attention

### ISSUE THREAD

**Issue by deepkotecha** [deepkotecha/qr-code#8]
**error**: book is not abstract and does not override abstract method actionPerformed(ActionEvent) in ActionListener
 class book extends Frame implements ActionListener{
 ^
deep.java:10: error: cannot find symbol
	Label l2=new label("From: ",Label.LEFT);
	             ^
  symbol:   class label
  location: class book
deep.java:11: error: cannot find symbol
	Label l3=new label("To: ",Label.LEFT);
	             ^
  symbol:   class label
  location: class book
deep.java:12: error: cannot find symbol
	Label l4=new label("Depart: ",Label.LEFT);
	             ^
  symbol:   class label
  location: class book
deep.java:13: error: cannot find symbol
	Label l5=new label("Return: ",Label.LEFT);
	             ^
  symbol:   class label
  location: class book
deep.java:15: error: cannot find symbol
	Label l7=new label("Cabin: ",Label.LEFT);
	             ^
  symbol:   class label
  location: class book
deep.java:16: error: cannot find symbol
	Label l8=new label("Select Flight: ",Label.LEFT);
	             ^
  symbol:   class label
  location: class book
deep.java:17: error: cannot find symbol
	Label l9=new label("Passenger Name: ",Label.LEFT);
	             ^
  symbol:   class label
  location: class book
deep.java:18: error: cannot find symbol
	Label l10=new label("Age: ",Label.LEFT);
	              ^
  symbol:   class label
  location: class book
deep.java:19: error: cannot find symbol
	Label l11=new label("Mobile No: ",Label.LEFT);
	              ^
  symbol:   class label
  location: class book
deep.java:20: error: cannot find symbol
	Label l12=new label("Email: ",Label.LEFT);
	              ^
  symbol:   class label
  location: class book
deep.java:21: error: cannot find symbol
	Label l13=new label("Sex: ",Label.LEFT);
	              ^
  symbol:   class label
  location: class book
deep.java:33: error: cannot find symbol
		addWindowListener(new myWindowAdapter());
		                      ^
  symbol:   class myWindowAdapter
  location: class book
# **13 errors**

**Comment by smeetpatel** [comment]
@deepkotecha I've resolved those errors, just haven't updated it with this  repository.

**Comment by deepkotecha** [comment]
@smeetpatel Please push any changes you make, to the repository so that others can use that in future endeavors! Thanks in advance, Hope you understand. Cheers! :wheel_of_dharma:
